name:                hackerNews
version:             0.1.0.0
github:              "deepakkapiswe/hackerNews"
license:             BSD3
author:              "Deepak Kapiswe"
maintainer:          "deepakkapiswe@gmail.com"
copyright:           "2019 Deepak Kapiswe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DeepakKapiswe/hackerNews#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- http-conduit
- containers

library:
  source-dirs: src

executables:
  hackerNews-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hackerNews

tests:
  hackerNews-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hackerNews
